<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chauffeur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Chauffeur_model');
    } 

    /*
     * Listing of chauffeurs
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('chauffeur/index?');
        $config['total_rows'] = $this->Chauffeur_model->get_all_chauffeurs_count();
        $this->pagination->initialize($config);

        $data['chauffeurs'] = $this->Chauffeur_model->get_all_chauffeurs($params);
        
        $data['_view'] = 'chauffeur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new chauffeur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('matricule','Matricule','required|is_unique[chauffeurs.matricule]');
		$this->form_validation->set_rules('nom_complet','Nom Complet','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'matricule' => $this->input->post('matricule'),
				'nom_complet' => $this->input->post('nom_complet'),
				'contact' => $this->input->post('contact'),
            );
            
            $chauffeur_id = $this->Chauffeur_model->add_chauffeur($params);
            redirect('chauffeur/index');
        }
        else
        {            
            $data['_view'] = 'chauffeur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a chauffeur
     */
    function edit($cha_id)
    {   
        // check if the chauffeur exists before trying to edit it
        $data['chauffeur'] = $this->Chauffeur_model->get_chauffeur($cha_id);
        
        if(isset($data['chauffeur']['cha_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('matricule','Matricule','required|is_unique[chauffeurs.matricule]');
			$this->form_validation->set_rules('nom_complet','Nom Complet','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'matricule' => $this->input->post('matricule'),
					'nom_complet' => $this->input->post('nom_complet'),
					'contact' => $this->input->post('contact'),
                );

                $this->Chauffeur_model->update_chauffeur($cha_id,$params);            
                redirect('chauffeur/index');
            }
            else
            {
                $data['_view'] = 'chauffeur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The chauffeur you are trying to edit does not exist.');
    } 

    /*
     * Deleting chauffeur
     */
    function remove($cha_id)
    {
        $chauffeur = $this->Chauffeur_model->get_chauffeur($cha_id);

        // check if the chauffeur exists before trying to delete it
        if(isset($chauffeur['cha_id']))
        {
            $this->Chauffeur_model->delete_chauffeur($cha_id);
            redirect('chauffeur/index');
        }
        else
            show_error('The chauffeur you are trying to delete does not exist.');
    }
    
}
