<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Abonne_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get abonne by abo_id
     */
    function get_abonne($abo_id)
    {
        return $this->db->get_where('abonnes',array('abo_id'=>$abo_id))->row_array();
    }
    
    /*
     * Get all abonnes count
     */
    function get_all_abonnes_count()
    {
        $this->db->from('abonnes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all abonnes
     */
    function get_all_abonnes($params = array())
    {
        $this->db->order_by('abo_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('abonnes')->result_array();
    }
        
    /*
     * function to add new abonne
     */
    function add_abonne($params)
    {
        $this->db->insert('abonnes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update abonne
     */
    function update_abonne($abo_id,$params)
    {
        $this->db->where('abo_id',$abo_id);
        return $this->db->update('abonnes',$params);
    }
    
    /*
     * function to delete abonne
     */
    function delete_abonne($abo_id)
    {
        return $this->db->delete('abonnes',array('abo_id'=>$abo_id));
    }
}
