<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Charroi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get charroi by cha_id
     */
    function get_charroi($cha_id)
    {
        return $this->db->get_where('charrois',array('cha_id'=>$cha_id))->row_array();
    }
    
    /*
     * Get all charrois count
     */
    function get_all_charrois_count()
    {
        $this->db->from('charrois');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all charrois
     */
    function get_all_charrois($params = array())
    {
        $this->db->order_by('cha_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('charrois')->result_array();
    }
        
    /*
     * function to add new charroi
     */
    function add_charroi($params)
    {
        $this->db->insert('charrois',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update charroi
     */
    function update_charroi($cha_id,$params)
    {
        $this->db->where('cha_id',$cha_id);
        return $this->db->update('charrois',$params);
    }
    
    /*
     * function to delete charroi
     */
    function delete_charroi($cha_id)
    {
        return $this->db->delete('charrois',array('cha_id'=>$cha_id));
    }
}
