<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chauffeur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get chauffeur by cha_id
     */
    function get_chauffeur($cha_id)
    {
        return $this->db->get_where('chauffeurs',array('cha_id'=>$cha_id))->row_array();
    }
    
    /*
     * Get all chauffeurs count
     */
    function get_all_chauffeurs_count()
    {
        $this->db->from('chauffeurs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all chauffeurs
     */
    function get_all_chauffeurs($params = array())
    {
        $this->db->order_by('cha_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('chauffeurs')->result_array();
    }
        
    /*
     * function to add new chauffeur
     */
    function add_chauffeur($params)
    {
        $this->db->insert('chauffeurs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update chauffeur
     */
    function update_chauffeur($cha_id,$params)
    {
        $this->db->where('cha_id',$cha_id);
        return $this->db->update('chauffeurs',$params);
    }
    
    /*
     * function to delete chauffeur
     */
    function delete_chauffeur($cha_id)
    {
        return $this->db->delete('chauffeurs',array('cha_id'=>$cha_id));
    }
}
