<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commande_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commande by com_id
     */
    function get_commande($com_id)
    {
        return $this->db->get_where('commandes',array('com_id'=>$com_id))->row_array();
    }
    
    /*
     * Get all commandes count
     */
    function get_all_commandes_count()
    {
        $this->db->from('commandes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all commandes
     */
    function get_all_commandes($params = array())
    {
        $this->db->order_by('com_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('commandes')->result_array();
    }
        
    /*
     * function to add new commande
     */
    function add_commande($params)
    {
        $this->db->insert('commandes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commande
     */
    function update_commande($com_id,$params)
    {
        $this->db->where('com_id',$com_id);
        return $this->db->update('commandes',$params);
    }
    
    /*
     * function to delete commande
     */
    function delete_commande($com_id)
    {
        return $this->db->delete('commandes',array('com_id'=>$com_id));
    }
}
