<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Zone_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get zone by zone_id
     */
    function get_zone($zone_id)
    {
        return $this->db->get_where('zones',array('zone_id'=>$zone_id))->row_array();
    }
    
    /*
     * Get all zones count
     */
    function get_all_zones_count()
    {
        $this->db->from('zones');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all zones
     */
    function get_all_zones($params = array())
    {
        $this->db->order_by('zone_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('zones')->result_array();
    }
        
    /*
     * function to add new zone
     */
    function add_zone($params)
    {
        $this->db->insert('zones',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update zone
     */
    function update_zone($zone_id,$params)
    {
        $this->db->where('zone_id',$zone_id);
        return $this->db->update('zones',$params);
    }
    
    /*
     * function to delete zone
     */
    function delete_zone($zone_id)
    {
        return $this->db->delete('zones',array('zone_id'=>$zone_id));
    }
}
